# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  database: ninabreznik_test
  encoding: utf8

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  database: esova-production
  encoding: utf8
